### ISSUE TITLE
RFC: Use black for code formatting

### ISSUE THREAD

**Issue by sloria** [marshmallow-code/marshmallow#1104]
Let's spend less time formatting code and let the computer do it.

I've been using black in other projects and it's worked nicely. Integrates with pre-commit, has plugins for all the popular editors.

I've held off on black to avoid creating conflicts for existing PRs. But we have a relatively low number of PRs right now, so maybe now's a good time?

@lafrech @deckar01

**Comment by deckar01** [comment]
We started using it at work on a large legacy code base a few months ago. The only gotcha we ran into is that we had to pin the black version in our dev requirements, because the output can differ between minor versions while it is in beta. Fixing merge conflicts was pretty straight forward. Rebase, keep my changes, run black, continue rebase.

A quick check indicates that the changes will be about half quotes and half line wrapping.

**Comment by sloria** [comment]
I've been using `pre-commit` to run black, which requires you to pin the version anyway. Example: https://github.com/marshmallow-code/webargs/blob/1c2f034f03baca3ab582ec881d572bb8290a61f6/.pre-commit-config.yaml#L2-L6 . I don't add black to dev requirements.

**Comment by lafrech** [comment]
No objection to this kind of things.

The only issue have is that I use Debian Stretch at work and at home (I might go for testing at home before it gets stable), and therefore I work on Python 3.5. Because I never needed to use a more recent Python and because I deploy on 3.5.

This might prevent me to run pre-commit (https://github.com/marshmallow-code/webargs/pull/244) unless I use 3.6 to develop using pyenv, which I'd rather avoid.

No big deal. I can fix my mess after CI fails on my PRs.

**Comment by sloria** [comment]
@lafrech You could run pre-commit in Docker. Here's an [image](https://hub.docker.com/r/sloria/pre-commit) for running it on Python 3.6.

```bash
docker pull sloria/pre-commit:py36
# In a repo with a .pre-commit-config.yaml
docker run --rm -v $(pwd):/root sloria/pre-commit:py36
```

EDIT: Use python 3.6
EDIT 2: Fix link

**Comment by madsmtm** [comment]
@deckar01, this will (hopefully) change soon, when a full release is made, see ambv/black#517
