### ISSUE TITLE
Is version 3 stable ?

### ISSUE THREAD

**Issue by lovasoa** [marshmallow-code/marshmallow#1154]
The documentation points to the unreleased 3.0 release. The README instructs users to install 3.0.
My question is:
 - Is marshmallow 3.0 stable ?
    - If it is, then why isn't it released ?
    - If it is not, then why incentivize users to use it ?

As a maintainer of [marshmallow-dataclass](https://pypi.org/project/marshmallow-dataclass/), a library that depends on marshmallow, should I also push users to use the unreleased 3.0 version of marshmallow ?

**Comment by lafrech** [comment]
v3 is in release candidate state, so it is close to stable.

There is still a few things to do before releasing: https://github.com/marshmallow-code/marshmallow/milestones/3.0

This is benevolent work. We can't provide any ETA.

Users starting a new project are encouraged to use v3 because the few breaking changes that may be introduced should be less trouble than the 2 to 3 migration when v3 is released. Besides, using v3, they can identify limitations or issues and bring improvements before the stable release.

Developers of marshmallow-based libraries are encouraged to start porting the code to marshmallow 3. Some libraries of the environment (apispec, webargs,...) support both versions, which is the ideal case, but it is not always easy to achieve. I've started a marshmallow 3 branch on umongo (https://github.com/Scille/umongo/tree/marshmallow_3) that doesn't support marshmallow 2.
