### ISSUE TITLE
With SQLAlchemy, related objects are always loaded, regardless of Meta.fields, only param, or exclude param

### ISSUE THREAD

**Issue by sloat** [marshmallow-code/marshmallow#12]
SQLAlchemy triggers a query when the attribute is accessed with  `getattr` in [utils.to_marshallable_type](https://github.com/sloria/marshmallow/blob/dev/marshmallow/utils.py#L71)  

I know that it is done this way to keep it non-specific to one ORM -- but would it be possible to pass one (or all) of the Meta.fields, only, or exclude lists to this function? 

I don't have time to investigate further at the moment, but I'll try to work up a patch tonight.

**Comment by dmckeone** [comment]
I am seeing this as well on Python 2.7.5 w/ SQLAlchemy 0.8 models.  It seems to have been broken as of https://github.com/sloria/marshmallow/commit/6032e910fb9bcd38f3691b5bc2a2e43873cd5a36 due to different behaviour between the comprehension and the use of **dict**.

Calling getattr() on all objects has a number of side-effects for my models, so, at least for me, this isn't preferable (or efficient) behaviour.  A filter that only gets values for the attributes I've asked for from the serializer would be more suitable for my needs.

**Comment by sloria** [comment]
Fixed. utils.to_marshallable_type will only access the attributes that are necessary, based on the Meta options, `only`, and `exlude` params.

Thanks for reporting this!
