### ISSUE TITLE
Can marshmallow provide a model class serializer like the django rest framework?

### ISSUE THREAD

**Issue by luli817** [marshmallow-code/marshmallow#1434]
```python
class BookInfoSerializer(serializers.ModelSerializer):
    """book model class serializer"""
    class Meta:
        model = BookInfo
        fields = ('id', 'btitle', 'bpub_date')
```

**Comment by luli817** [comment]
`class BookInfoSerializer(serializers.ModelSerializer):
    """图书数据序列化器"""
    class Meta:
        model = BookInfo
        fields = ('id', 'btitle', 'bpub_date')`

**Comment by lafrech** [comment]
Please post in english.

**Comment by sloria** [comment]
marshmallow is agnostic to ORMs by design. Integrations are written as separate packages. See https://github.com/marshmallow-code/marshmallow/wiki/Ecosystem#orm-integration for a listing of these.

**Comment by deckar01** [comment]
If you have a custom model class, the docs suggest using the `@post_load` decorator  to make `load()` output class instances.

https://marshmallow.readthedocs.io/en/stable/quickstart.html#deserializing-to-objects

The proposed syntax is already used by some marshmallow extensions to generate the fields and load to model instances.

---

Side note: I kind of like the idea of assigning a model to a schema declaratively. It is not very easy to make a utility to do this due to the way `post_load` gets locked in at declaration time. When I was toying around with Marsha, I started with the premise that all data has a model and just allowed the default model to be generic (like `dict` or `dataclass`) for convenience.
