### ISSUE TITLE
Building a more granular level of validation errors

### ISSUE THREAD

**Issue by ashwani99** [marshmallow-code/marshmallow#1499]
I have been using marshmallow for some of my projects and I am facing this issue of discriminating between different types  `schema` errors and `field` errors. Differentiating between `schema` and `field` errors are easy as we can just check for the key `_schema` is present or not in `ValidationError.messages`

Now if you want to see if the `ValidationError` instance is hinting a `missing value` error or a `invalid email address error` or a `unknown field` error, I have not found a way other than comparing the message __strings__

If there is a additional field for type of error it would be very much useful to give a better feedback of the error in the application. Thoughts?

**Comment by ashwani99** [comment]
Also, I am curious if this behavior is correct. As per the [documentation](https://marshmallow.readthedocs.io/en/stable/api_reference.html#module-marshmallow.exceptions) of `ValidationError`,
> field_name – Field name to store the error on. If None, the error is stored as schema-level error.

But if I try the following code:
```python
class TestSchema(Schema):
    id = fields.Number(required=True)

    def handle_error(self, exc, data, **kwargs):
        print('field name:', exc.field_name)
        print('error messages:', exc.messages)

>>> my_schema = TestSchema()
>>> my_schema.load({}) # data is missing
field name: _schema
error messages: {'id': ['Missing data for required field.']}
...
>>> my_schema.load(None) # invalid type
field name: _schema
error messages: {'_schema': ['Invalid input type.']}
...
>>> my_schema.load({'id': 'hello'}) # valid input, but value of `id` is not `Number`
field name: _schema
error messages: {'id': ['Not a valid number.']}
...
```

In all of the above examples, the `field_name` is `_schema`, even for the last two examples where the error is on a `field`. Should not the `field_name` be `id` for the last two examples?

**Comment by deckar01** [comment]
This behavior is intentional. The `field_name` you pass to `ValidationError` is only needed in contexts where the field name can't be inferred. Notice in the docs, even when custom field validators are used, the `field_name` doesn't have to be explicitly specified, yet the error we raise uses the correct key matching the field name.

https://marshmallow.readthedocs.io/en/stable/quickstart.html#validation

A `ValidationError` will never bubble to the user from a field, we always collect them into a dict so that they can all be raised as a single error in the structure of the top-level schema. Probing the message dict's keys is necessary to differentiate between field and schema errors.
