### ISSUE TITLE
pre_load many has issues in 3.5.0

### ISSUE THREAD

**Issue by mikebarkmin** [marshmallow-code/marshmallow#1527]
In marshmallow 3.4.0 data is a list, which is what I expect, when using pass_many.

In marshmallow 3.5.0 data is a single object.

```
   @pre_load(pass_many=True)
    def reposition_tasks(self, data, **kwargs):
        position = 0
        for task in data:
            task["position"] = position
            position += 1
        return data
```

Do you have a suggestion, what I am doing wrong? Or is this a bug?

**Comment by sloria** [comment]
Is your schema nested within another schema? If so, see that the behavior was changed when doing `List(Nested(...)`: https://github.com/marshmallow-code/marshmallow/blob/dev/CHANGELOG.rst#350-2020-02-19

**Comment by michaeltoohig** [comment]
I also ran into this problem.

Using version 3.4.0 or below I've been defining a nested schema with the `List` field.

 ```
class MyChildSchema(Schema):
    name = fields.Str()

    @pre_load(pass_many=True)
    def pre_load(self, data, many, **kwargs):
        data = self.do_something(data)
        return data

class MySchema(Schema):
    group = fields.Str()
    items = fields.List(fields.Nested(MyChildSchema))
```

and the `List(Nested(MyChildSchema))` would make sure I sent a list of items to the `@pre_load` method. Since version 3.5.1 that doesn't seem to be the case and the `pre_load` doesn't send the list of items any longer which would cause the error. So when I found this issue and read your link to the changelog and followed the linked issue and read more I changed `items` to `Nested(MyChildSchema, many=True)` which makes things work again. But using `List(Nested(..., many=True))` does not work also.

So what is the purpose of the `fields.List` now that I can use `Nested(..., many=True)`? Is `List` depreciated or did I miss something else in the changelog that would clarify this? I believe I was following documentation when I first wrote the field so is that now out of date?

**Comment by lafrech** [comment]
I didn't get the time yet to investigate this issue.

@michaeltoohig : On the contrary, `Nested(many)` will be deprecated in favor of `List(Nested())`.

**Comment by michaeltoohig** [comment]
@lafrech Okay well I have to second this issue then and I just double checked my work. `List(Nested(Schema))` does not work with `pre_load` on the child schema because it passes single objects instead of the many objects as it would before.

However, if I think about it a bit more I realize this means that I should change my `do_something` logic to handle each individual item instead of the whole list at once which makes more sense IMO. Before I was using the bug instead of fixing it and I see it now. 

But perhaps the 'issue' I was facing could be a legitimate issue for another use case?

Thanks @lafrech and @sloria

**Comment by lafrech** [comment]
The change in 3.5.0 (reverting the `List(Nested())` optim) modifies the way the nested schema is called. It used to be called once for the list and it is now called once per item. This is documented in the changelog.

I think the issue here is in user code: both examples provided above use `pass_many=True` but only manage one single case (the `many=True` case). The decorated functions should handle both many=True/False cases (using a condition on the `many` argument) for the schema to be fully functional. The code worked because the case that was explicitly handled was the only case the schema was used for. But since the change in 3.5.0, the schema is used for the other case.

My advice would be to always manage both many cases in decorated functions when using `pass_many=True`. I'm pretty sure the upgrade to 3.5.0 would have been seamless if both example codes above had managed both many cases.

**Comment by lafrech** [comment]
I think the question is answered. New behaviour is the correct one.
