### ISSUE TITLE
Adding location like header in Schema body

### ISSUE THREAD

**Issue by priyanshu20** [marshmallow-code/marshmallow#1540]
So i need to add the authorization bearer model in the header part of a json request
can i validate it with the marshmallow schema?

**Comment by deckar01** [comment]
If the headers structure inherits from the `Mapping` interface, marshmallow will consume it. If it doesn't, you will need to cast it to a dict first. You will probably need to set ~~`unknown=IGNORE`~~ `unknown=EXCLUDE` on the schema, since you probably don't want to declare the entire HTTP headers spec.

flask/werkzeug's `Headers` data structure does not inherit from `Mapping`, but casting it to a dict works fine.

**Comment by lafrech** [comment]
s/IGNORE/EXCLUDE
