### ISSUE TITLE
marshmallow3 on pypi?

### ISSUE THREAD

**Issue by jcampbell** [marshmallow-code/marshmallow#1659]
Hi Marshmallow team!

We updated our library [Great Expectations](https://github.com/great-expectations/great_expectations) to use marshmallow 3 several months ago, but we're finding fairly consistent incompatibilities in declared requirements, for example with Google Composer because of airflow and flask dependencies.

I see that pypi hosts a marshmallow2 package. Is it possible to publish a marshmallow3 on which we could declare our dependency in order to coexist with packages who have declared marshmallow < 3 in their requirements?

(Or, is there another workaround you recommend?)

Thank you!

**Comment by lafrech** [comment]
Hi.

Marshmallow 2 has reached EOL. We only release marshmallow 3+ versions.

AFAIK, marshmallow2 is a third-party package maintained by someone out of the marshmallow-code organization who uses marshmallow 2 and is willing to share his work. Except the package on pypi is an old marshmallow 2 version, not up to date with the latest marshmallow 2 releases.

We should probably ask him to modify his README to reflect that because it reads like it is released by us. Or even remove the package.

I'm tempted to say libraries should not depend on marshmallow 2 since it is EOL. They may be happy with a third-party effort to maintain marshmallow 2 but this one doesn't seem to be maintained either.

**Comment by jcampbell** [comment]
Thanks for the quick response. I very much understand the need to drop support for marshmallow 2 (and I really like the changes in the new api). Unfortunately, that leaves us kind of caught in the middle of the heavyweights like GCP.

The best option I'm aware of at this point would be to repackage marshmallow 3 ourselves; are you aware of any other options we should pursue?

**Comment by deckar01** [comment]
Have you tried upgrading Airflow? It looks like you are [pinned](https://github.com/great-expectations/great_expectations/blob/f532aae50024e37a562559df1933d7fb5445cfc3/setup.py#L26) to [a version from 2017](https://github.com/apache/airflow/releases/tag/1.9.0). It [sounds like they upgraded to v3](https://github.com/apache/airflow/pull/9473#issuecomment-654406329) in the last few months and have [cut releases since then](https://github.com/apache/airflow/releases/tag/1.10.12).

I don't think marshmallow is a dependency of flask, so I assume it is a transient dependency conflict, but unrelated to marshmallow. If any of your other dependencies have not updated to marshmallow 3, let me know and I will see if I can help them.

**Comment by jcampbell** [comment]
You're absolutely right about the outdated dependency declaration in our optionals; I'll update that. 

The issue, again though, is that there are a large number of existing packages that have declared dependencies on marshmallow 2--including airflow until quite recently--and without independently-named packages we cannot coexist in the same environment as those packages.

More specifically, in the case of airflow, many users rely on managed deployments (such as [Google Cloud Composer](https://cloud.google.com/composer/docs/concepts/versioning/composer-versions)) which do not allow them to upgrade their deployed airflow version (specifically, the most recent available version of airflow on composer is 1.10.9, but many users have dependencies requiring even earlier versions).

**Comment by deckar01** [comment]
I was reading [PEP 440](https://www.python.org/dev/peps/pep-0440/#inclusive-ordered-comparison) wrong. You are on the latest version of `apache-airflow`. Sorry for the confusion.

It looks like `apache-airflow` fixed this issue [in their `master` branch 2 months ago](https://github.com/apache/airflow/pull/9648), but the commits have not actually made it into a stable release yet. More confusion on my part, more apologies. You could pin yourself to one of their nightly tags or a specific commit until they cut the next release. Another option might be to override the `flask-appbuilder` version in your `airflow` extra to use v3.

**Comment by jcampbell** [comment]
Thanks, @deckar01 -- I'll continue to follow this. For now, I've essentially statically linked us to a pinned version of marshmallow by including it in GE. I hate to have to do it, but don't see an alternative yet.

Bottom line of course is just that you all are too popular! :)

**Comment by jcampbell** [comment]
Please feel free to close the issue if you're definitely not interested in distributing marshmallow3 under a new package name (as well as the old one)!
