### ISSUE TITLE
Is it intentional that setting parameter unknown=<any non-empty string> behaves the same as unknown=EXCLUDE?

### ISSUE THREAD

**Issue by chaynsaw** [marshmallow-code/marshmallow#1721]
I was playing around with some of the unknown options and noticed that if you set unknown to a random string when instantiating a schema, it behaves the same as setting `unknown=EXCLUDE`.

Is this intentional? 

```
class TestSchema(Schema):
    schema_field = fields.Str(required=True)

test = dict(schema_field="random", non_schema_field="also random")
schema = TestSchema(unknown=EXCLUDE)
print(schema.load(test))
# {'schema_field': 'random'}
```

```
schema = TestSchema(unknown=INCLUDE)
print(schema.load(test))
# {'schema_field': 'random', 'non_schema_field': 'also random'}
```

```
schema = TestSchema(unknown="1234")
print(schema.load(test))
# {'schema_field': 'random'}
```

**Comment by lafrech** [comment]
Not intentional.

It happens here: https://github.com/marshmallow-code/marshmallow/blob/5230121aa173e4907c06c485f9da85c0e749c263/src/marshmallow/schema.py#L679-L693

We could raise an exception (or should it be a warning ? I'd go for an exception) if a wrong parameter is passed.

But the API contract is that the user is not supposed to pass a string but a singleton.

```py
    from marshmallow import INCLUDE  # <- this is what you pass
```

**Comment by chaynsaw** [comment]
Do you think the above commit would suffice? IE, worth opening a PR over?
