### ISSUE TITLE
Cannot execute importlib.reload from 2.21.0 to 3.10.0?

### ISSUE THREAD

**Issue by sakaia** [marshmallow-code/marshmallow#1738]
I try to execute importlib.reload from 2.21.0 to 3.10.0.
But the version changes from 3.10.0 to 3.9.0 works fine.
Is there any workaround for switching marshmallow version switching?

Also If this issue should goes to cpython(importlib), please suggest me.

```
# test

import sys, subprocess
import importlib
import marshmallow
print(marshmallow.__version__)
result = subprocess.check_output([sys.executable, '-m', 'pip', 'install', '--user', 'marshmallow==3.10.0'])
importlib.reload(marshmallow)
print(marshmallow.__version__)
```
Output is follows

```
2.21.0
Traceback (most recent call last):
  File "modtest.py", line 9, in <module>
    importlib.reload(marshmallow)
  File "/usr/lib/python3.6/importlib/__init__.py", line 166, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 618, in _exec
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/zdlsadmin/.local/lib/python3.6/site-packages/marshmallow/__init__.py", line 12, in <module>
    from marshmallow.utils import EXCLUDE, INCLUDE, RAISE, pprint, missing
ImportError: cannot import name 'EXCLUDE'
```

**Comment by deckar01** [comment]
> If a module imports objects from another module using `from … import …`, calling `reload()` for the other module does not redefine the objects imported from it — one way around this is to re-execute the from statement, another is to use import and qualified names (_module.name_) instead.

https://docs.python.org/3/library/importlib.html#importlib.reload

This is expected behavior. `reload` only evaluates a single file and does not offer a utility for recursive reloading. I suspect the confusion is that `marshmallow` is a "package" made up of many "modules", but importing and reloading `marshmallow` is magically resolved to the `marshmallow.__init__` module.

IPython's `deepreload` package works well for this task.

https://ipython.org/ipython-doc/stable/api/generated/IPython.lib.deepreload.html
