### ISSUE TITLE
And validator

### ISSUE THREAD

**Issue by rugleb** [marshmallow-code/marshmallow#1768]
Hello everyone!
I would like to add a new validator to combine multiple validators into one. Simple example:

```py
def calculate_age(birthday: date) -> int:
    today = date.today()
    offset = (today.month, today.day) < (birthday.month, birthday.day)
    return today.year - birthday.year - offset

def validate_not_future_date(value: date) -> None:
    if value > date.today():
        raise ValidationError("Not future date.")

def validate_14_years_old(value: date) -> None:
    if calculate_age(value) < 14:
        raise ValidationError("Must be 14 years old.")

class PassportSchema(Schema):
    issued_at = fields.Date(
        "%Y-%m-%d",
        validate=[
            validate_not_future_date,
            validate_14_years_old,
        ],
    )

    @post_load
    def make_passport(self, data: dict, **kwargs) -> Passport:
        return Passport(**data)

@attr.s(auto_attribs=True, slots=True, frozen=True)
class Passport:
    issued_at: date

    def __attrs_post_init__(self) -> None:
        validate_not_future_date(self.issued_at)
        validate_14_years_old(self.issued_at)
```

In this example, I am forced to pass validators as a list in the `issued_at` field (in `PassportSchema`) and call two functions to validate a single value in `Passport` entity.
I would like to combine the two functions into one and turn them into a single validator:

```py
T = TypeVar("T")

Validator = Callable[[T], T]

@attr.s(auto_attribs=True, slots=True, frozen=True)
class _AndValidator:
    validators: Sequence[Validator]

    def __call__(self, value: T) -> T:
        for validator in self.validators:
            validator(value)
        return value

def and_validator(*validators) -> _AndValidator:
    return _AndValidator(validators)

validate_passport_issued_at = and_validator(
    validate_14_years_old,
    validate_not_future_date,
)
```

Then the example above will look much more concise:

```py
class PassportSchema(Schema):
    issued_at = fields.Date("%Y-%m-%d", validate=validate_passport_issued_at)

    @post_load
    def make_passport(self, data: dict, **kwargs) -> Passport:
        return Passport(**data)

@attr.s(auto_attribs=True, slots=True, frozen=True)
class Passport:
    issued_at: date

    def __attrs_post_init__(self) -> None:
        validate_passport_issued_at(self.issued_at)
```

I would like to add such functionality to the `marshmallow.validate` package.

**Comment by deckar01** [comment]
The `validate` parameter already supports this:

> class marshmallow.fields.Field
> Parameters:
>   * validate – Validator **or collection of validators** that are called during deserialization.

https://marshmallow.readthedocs.io/en/stable/marshmallow.fields.html#marshmallow.fields.Field

```py
class PassportSchema(Schema):
    issued_at = fields.Date("%Y-%m-%d", validate=[validate_14_years_old, validate_not_future_date])
```

**Comment by rugleb** [comment]
I know. In addition, I indicated this in the example and explained that it is not always very convenient.

**Comment by lafrech** [comment]
Rather than

```py
validate_passport_issued_at = and_validator(
    validate_14_years_old,
    validate_not_future_date,
)
```

you can write

```py
def validate_passport_issued_at(value):
    validate_14_years_old(value)
    validate_not_future_date(value)
```

Is it much worse?

I think I understand why you find the former more elegant, but the latter works fine. Besides you use case seems specific to `attrs`. As @deckar01 pointed out, a list of validators is accepted in a field and in most cases, this is enough. I don't think the feature is worth the added API.


Well, the difference between passing a single function and relying on the existing multiple validators feature is that the latter will execute both validators and return all errors while the former will raise at the first failed validation. This could be addressed by a `And` validator but again, this seems specific to frameworks / use cases outside of marshmallow's main use. Since it can be achieved in user code for anyone needing it for his framework, I'm leaning towards not doing it in marshmallow.


If you end up doing it in your code, mind my remark above about collecting errors about all validators. You're more than welcome to share your implementation here in case it helps anyone.

**Comment by rugleb** [comment]
Of course, I can write it that way. It's less elegant. The difference is that I will have to create a function specifically. In my version, this will not have to be done.

> Besides you use case seems specific to attrs

No, it seems. I just gave it as an example.
In practice, we often write libraries where validation functions can be found everywhere, not only in schemas.
Now we have to duplicate them and write ugly functions like yours.

> This could be addressed by a And validator but again, this seems specific to frameworks / use cases outside of marshmallow's main use. 

I just gave *an example* of implementation. The details are worth thinking about later, if my offer is accepted.

> If you end up doing it in your code, mind my remark above about collecting errors about all validators.

Of course.

**Comment by deckar01** [comment]
We generally avoid adding surface area to the core API when the functionality is already supported and the benefit is syntax preference. This helps keep the code easy to maintain and the documentation easy to understand.

An alternative you might consider is declaring your combined validator as an iterable to avoid having to inline it.

```py
validate_passport_issued_at = (
    validate_14_years_old,
    validate_not_future_date,
)

class PassportSchema(Schema):
    issued_at = fields.Date("%Y-%m-%d", validate=validate_passport_issued_at)
```

You can compose these as needed with python's arg unpacking syntax `*`.

```py
foo = (bar, baz)
snap = (crackle, pop)
validators = (*foo, *snap)
```

If you are interested in publishing this module as a python package, we would be happy to add it to the [community ecosystem](https://github.com/marshmallow-code/marshmallow/wiki/Ecosystem) to help other users discover it.

**Comment by rugleb** [comment]
> An alternative you might consider is declaring your combined validator as an iterable to avoid having to inline it.

Are you serious? This is not an alternative to what I suggest. You can't call `validate_passport_issued_at` because it's a tuple! What's the point of your alternative? I'm talking about reusability. This function (sorry, tuple 🤮) from your suggest cannot be reused outside of the schema! 
You don't even try to understand what I have to offer.

Opening this PR, I expected to hear the constructive opinion from professionals and receive a clear answer: "yes, let's do it" or "no". Not a set of ugly alternatives.

I'm sorry to have taken up your time (and sorry for my English).

**Comment by deckar01** [comment]
@rugleb Please review our code of conduct. Your behavior is inappropriate. Please be respectful to other users.

https://marshmallow.readthedocs.io/en/dev/code_of_conduct.html

**Comment by deckar01** [comment]
To summarize the request as I understand it now, you would like to compose validators together declaratively and also be able to call the result directly so that it can be used by a validation system outside of marshmallow.

With that objective in mind, another solution would be to refactor the [`Field._validate()`](https://github.com/marshmallow-code/marshmallow/blob/7abba85/src/marshmallow/fields.py#L244) method into the desired "and" validation utility. In [`Field.__init__()`](https://github.com/marshmallow-code/marshmallow/blob/7abba85/src/marshmallow/fields.py#L173-L178) instead of storing a list of `validators` so that we can loop on them later, we could store a callable and use the utility to build the "and" validator when the argument is iterable. This would avoid needing to construct an error list and a kwargs dict for every field during the `_validate()` call when the validator is a single method or empty, so this could have a positive performance impact on loading.

**Comment by sloria** [comment]
I like your proposal, @deckar01. Would you be up for a PR to prove the concept?

**Comment by sloria** [comment]
Actually, I took a stab at this in #1777.

**Comment by rugleb** [comment]
Amazing! Thank you!
