### ISSUE TITLE
`unknown = RAISE` ignored with workarounds for lack of validation in `.dump()`

### ISSUE THREAD

**Issue by ghost** [marshmallow-code/marshmallow#1771]
First of all, thanks for the library!

Not sure if this is a question or a feature request but I couldn't find anything on this specific case in the various existing issues on the lack of validation in `dump()` nor one close enough where this could serve as a comment (except for #1450 but it got closed immediately by the author without further info).

Similarly to #1415, we're starting to use Marshmallow schemas for validating and serializing outgoing/response data as well; so we can ensure their structure, data formats and can auto-generate the response part of the API docs from them.  Unfortunately for this use-case, `.dump()` doesn't validate the data it receives but the workarounds I could find for that don't seem to work with `unkown = RAISE`.

Doing a `.load()` before `.dump()` doesn't work for us as the data structure won't (always) be simple enough that `.load()` will accept them (e.g. containing objects).

Doing a `.load()` (or `.validate()`) after `.dump()` can work for us, however it won't catch any unknown fields when `unknown = RAISE` is used (as these fields have been silently removed by `.dump()` already).

The only workaround I can see for this is adding any keys that were in the input but aren't in the result from `.dump()` into a copy of the result and running *that* through `.validate()` instead, but that seems rather ugly.  Is there a better solution for this?

Code to reproduce (including the ugly workaround):

<details>

```py
import marshmallow

class MySchema(marshmallow.Schema):
    foo = marshmallow.fields.String()

    class Meta:
        unknown = marshmallow.RAISE

response = {'foo': 1, 'bar': 2}
schema = MySchema()

# Would expect an error here
response_dumped = schema.dump(response)
# or here
errors = schema.validate(response_dumped)
print(f'errors: {errors}')

# Ugly workaround
for_validation = response_dumped.copy()
for k in response:
    if k not in for_validation:
        for_validation[k] = None
errors = schema.validate(for_validation)
print(f'errors: {errors}')
```
</details>

**Comment by lafrech** [comment]
The dump eliminates the unknown keys and therefore ensures they don't leak through the API.

This could be enough to secure your API.

IIUC, you want a mean to check that there were no unknown keys in the inputs in the first place.

I don't see a simple way to do that in marshmallow because it is meant to dump objects so there is no list of attribute, we just iterate on the schema fields and pull the attributes/items from the object to dump.

I don't think what you want to do can be done achieved on objects. When working with dicts you can indeed check for unknown keys in a separate step. You could just compare you inputs dict keys versus schema fields (or field attribute if applicable).
