### ISSUE TITLE
Marshmallow fails to validate Nested field of db.relationshiop from Flask-SQLAlchemy

### ISSUE THREAD

**Issue by sbalasa** [marshmallow-code/marshmallow#1947]
Am using relationship in Flask-SQLAlchemy, marshmallow fails to validate it:

```
# Model
labels = db.relationship("Label", back_populates="items")

# Schema
class LabelSchema(Schema):
    name =. fields.Str(required=True)

labels = fields.Nested(LabelSchema, many=True)

# Input of this field from REST Post body
"labels": "laptop, mobile"

# Error
labels: ["Invalid Type"]
```

**Comment by deckar01** [comment]
> "labels": "laptop, mobile"

The value appears to be a string instead of a list, which is what `fields.Nested(many=True)` expects. I would recommend creating a custom field that extends `fields.List._deserialize` to parse `"laptop, mobile"` into `["laptop", "mobile"]`.

https://marshmallow.readthedocs.io/en/stable/custom_fields.html

> name = fields.Str(required=True)

Also, you are missing a step needed to nest the label name into a dict that can be loaded by the label schema. You can wrap the `LabelSchema` with a `Pluck` field to declare this transformation.

https://marshmallow.readthedocs.io/en/stable/marshmallow.fields.html?highlight=pluck#marshmallow.fields.Pluck

```py
from marshmallow import fields, Schema


class LabelSchema(Schema):
    name = fields.Str(required=True)

class StringList(fields.List):
    def _deserialize(self, value, attr, data, **kwargs):
        value = [item.strip() for item in value.split(',')]
        return super()._deserialize(value, attr, data, **kwargs)


class Test(Schema):
    labels = StringList(fields.Pluck(LabelSchema, 'name'))


Test().load({'labels': 'laptop, mobile'})
# {'labels': [{'name': 'laptop'}, {'name': 'mobile'}]}
```

**Comment by sbalasa** [comment]
Thanks @deckar01
