### ISSUE TITLE
[Question] Is it possible to have `fields.Boolean` failing on `1.0` (or other numeric types etc)

### ISSUE THREAD

**Issue by symonk** [marshmallow-code/marshmallow#2001]
The reason I ask is, I've seen an API bug in the past where I (naively) had fields set as `Boolean` where the api response was explicitly `true` & `false` however we regressed and I missed a case as the api started returning `1` and with bool being a subclass of int this slid through until it hit production and our customers found it (while probably using an api wrapper that was not written in python or was more strict.

I noticed the `truthy=` & `falsy=` parameters which seemed appealing, however they use `in` checks and `1.0 in {True}` is still fine when setting `truthy={True}` for example.

I Opted for a new `field.Field` that checks `value is True` or  `value is False` inside both `_serialise(...)` and `_deserialise(...)` which works nicely, I called it `StrictBoolean`.  

Is there a better way for handling such a case?  I had a look at the validators too which I guess creating my own `Validator` subclass would be a good idea too? but I think it's already converted to the `True` / `False` type before `__call__` is executed there too so when loading a field with value: `1.0` a validator on a `Boolean` field will receive `True` as its `value`.

Is this something that would be open to having an option for as part of the built in fields? Or if there is a better way to manage it, please let me know :) Thanks a lot for the hard work in marshmallow.

edit: I also cannot see `discussions` enabled - so apologies if this is the wrong place for a Question

**Comment by lafrech** [comment]
Hi. Don't worry, this is the right place.

By design choice, marshmallow only validates on deserialization, not serialization. The typical use case is the deserialization of untrusted data from the outside world in an API. When serializing, the data comes from internal code and is supposed to be correct. In other words, marshmallow is not meant to catch internal errors.

It will catch internal errors incidentally if the data type can't be coerced to the expected one, but marshmallow doesn't try to be smart about that and will let exceptions slip through.

You may use a custom field for this specific need but this is not something I would engage into.

**Comment by symonk** [comment]
Thanks @lafrech i guess testing an API in an end2end setting is not advisable then and we _shouldn't_ be using it for that; tho with a few work arounds its been working well
