### ISSUE TITLE
tests are not included in release tarballs

### ISSUE THREAD

**Issue by danc86** [marshmallow-code/marshmallow#201]
Please include the tests directory in release tarballs. You can probably just add:

```
include tests
```

to `MANIFEST.in`. This will make it easy for downstream distro packagers to run the tests as part of the build process.

You might also consider adding the docs and examples to the tarballs in the same way.

**Comment by philtay** [comment]
In theory, including the tests in realease tarballs is good practice, but - in practice - it is not.
If you want to automate the build process for marshmallow I suggest you to download it from here

https://github.com/marshmallow-code/marshmallow/releases

instead of using PyPI. These tarballs include everything, source, tests, docs, etc.

If you are building packages in an isolated environment, using something like pbuilder, you can follow these (automatable) steps:
- install the build-time dependencies (using pip) listed here /dev-requirements.txt and here /docs/requirements.txt
- run the tests using tox from the root directory
- build the docs using /tasks.py
- create deb, rpm or whatever

A cool thing you can do is to contribute a Dockerfile for this project that automatically builds distro packages in a clean environment and put them in a volume.

**Comment by danc86** [comment]
> In theory, including the tests in realease tarballs is good practice, but - in practice - it is not.

Out of curiosity, why?

**Comment by davidism** [comment]
Because the distributions on PyPI have already been built, even if they are just sdists (tarballs).  If you're creating a package for a Linux distro, you should be building the package from the actual source, in your distro's environment.  Basically, the op is confusing a source distribution with _the_ source.

**Comment by danc86** [comment]
Conventionally source tarballs do include _all_ sources, even tests and docs and examples.

I wasn't suggesting to change the existing published tarballs, only to update `MANIFEST.in` so that future sdists will include the tests.

Anyway if you don't want to do that for some reason that's okay, I can just use the Github generated tarballs as suggested above.

Here's the Fedora package review which I just filed, if you're interested: https://bugzilla.redhat.com/show_bug.cgi?id=1219288

**Comment by Jenselme** [comment]
> Because the distributions on PyPI have already been built, even if they are just sdists (tarballs).

This is not a big deal, we can easily remove the egg-info. Moreover, it is easier to use pypi to get the soruces (github URLs are known to change from time to time). In fedora (and I guess in many other linux distros), many python packages are built from pypi. So I also think that tests and docs should be included in the tarballs. But, this is not a big issue.

**Comment by sloria** [comment]
This is a minimal change, and if it makes anyone's life easier, I'm happy to do it.

**Comment by danc86** [comment]
Thanks!
