### ISSUE TITLE
AssertionError: ({'errors': {'_schema': ['Invalid input type.']}}, 422)

### ISSUE THREAD

**Issue by NPZYMR** [marshmallow-code/marshmallow#2076]
https://stackoverflow.com/questions/74671699/assertionerror-errors-schema-invalid-input-type-422-mes

please check this link I'm facing this issue in marshmallow schema while sending json data.

**Comment by deckar01** [comment]
The first SO comment was on the right track. The second was wrong, `request.get_json()` should return a dict, so it was mocked correctly. It's not really clear what was erroring though. I tested that schema with that data and it works fine, so it is your test logic that is the problem. I do not see any evidence of an issue with marshmallow.

Since it appears you are using Flask, I would recommend using the test client that Flask provides.

https://flask.palletsprojects.com/en/2.2.x/testing/
