### ISSUE TITLE
fields.Nested Type Warning Since Version 3.15.0 

### ISSUE THREAD

**Issue by Fares-Abubaker** [marshmallow-code/marshmallow#2268]
Hi,

I'm encountering a warning from PyCharm related to `fields.Nested` after upgrading to `marshmallow` version 3.15.0. The warning states that `fields.Nested` expects a type `SchemaABC`, but it gets a type `[UserSerializer]` instead. This issue did not occur in earlier versions.

Here is a simple example to demonstrate the issue:

```python
from marshmallow import Schema, fields

class A(Schema):
    id = fields.Integer()

class B(Schema):
    a = fields.Nested(A)
```

**Warning:**
```
Expected type 'SchemaABC', got 'Type[A]' instead 
```

This warning appears when using `fields.Nested` with a schema class. It seems that the type checking introduced in version 3.15.0 does not recognize schema classes correctly.

Is there a new way to define nested schemas, or is this a bug that needs to be addressed?

Thank you for your help!

**Comment by lafrech** [comment]
Would you like to check with marshmallow 3.23.0? The typing here was slightly modified.

I don't understand why this would happen before the change and how that change would fix it, but you never know...

**Comment by skdavies** [comment]
I am also experiencing this issue on 3.23.1

I believe I figured out the cause of the issue. In the `Nested` code, this is the init function method signature:

```
def __init__(
        self,
        nested: SchemaABC
        | type
        | str
        | dict[str, Field | type]
        | typing.Callable[[], SchemaABC | type | dict[str, Field | type]],
        *,
        dump_default: typing.Any = missing_,
        default: typing.Any = missing_,
        only: types.StrSequenceOrSet | None = None,
        exclude: types.StrSequenceOrSet = (),
        many: bool = False,
        unknown: str | None = None,
        **kwargs,
    ):
```

Because of the way the multi line `|`'s are done, the IDE is interpreting `SchemaABC` as the only valid type for `nested`. To test this, I edited the file and moved it all to one long line and the warning went away. I'm not sure if this is more of a problem with PyCharm or Marshmallow. I do think this is a non-standard way to do multi-lines, and while it clearly works, it is usually more clear to use parentheses, which I believe would solve this issue.

**Comment by Fares-Abubaker** [comment]
@skdavies Great note, thanks for sharing it
I will open PR to fix it
