### ISSUE TITLE
Nested class can't process dict

### ISSUE THREAD

**Issue by leejaycoke** [marshmallow-code/marshmallow#30]
Hello~ at first, I'm sorry for my English

Why Nested field can't process dict? only accept instance it's inherited object. 

``` python
class Book(object):
    title = ''
    author = ''

class BookSerializer(Serializer):
    title = fields.String()
    author = fields.String()

class BookList(object):
    items = list()

class BookListSerializer(Serializer):
    items = fields.Nested(BookSerializer, many=True)
```

The solo BookSerializer class accept two types well. object and dic.
it's not problems.
for example

``` python
# 1st case which using object.
book = Book()
book.title = 'hello android'
book.author = 'leejaycoke'
return jsonify(BookSerializer(book).data)

# 2st case which using dict.
book = {'title': 'hello android', 'author': 'leejaycoke'}
return jsonify(BookSerializer(book).data)
```

But Nested fields can't accept dic for listing books but object is ok.
for example

``` python
# 1st case which using object
book1 = {'title': 'hello android', 'author': 'leejaycoke'}
book2 = {'title': 'hello iOS', 'author': 'tommy'}
book_list = BookList()
book.items = [book1, book2]
return jsonify(BookListSerializer(book).data)
"""
{
    "items": [
        {
            "title": "hello android",
            "author": "leejaycoke"
        },
        {
            "title": "hello iOS",
            "author": "tommy"
        }
    ]
}
"""

# 2st case which using dict it's failed
book1 = {'title': 'hello android', 'author': 'leejaycoke'}
book2 = {'title': 'hello iOS', 'author': 'tommy'}
book = {'items': [book1, book2]}
return jsonify(BookListSerializer(book).data)
"""
TypeError: Could not marshal nested object due to error:
"'builtin_function_or_method' object is not iterable"
If the nested object is a collection, you need to set "many=True".\
"""
```

can you help me?

**Comment by sloria** [comment]
Aha, this is tricky case. marshmallow serializes objects by pulling attributes or keys from objects that correspond to the names of a serializer's fields. So, a `Serializer` with a nested field named `items` will try to pull the `items` attribute or key from an object. This is fine for a plain object with an `items` _attribute_. 

However, when you try to serialize a dictionary with the same serializer, the serializer will again try to pull the `items` attribute from the dictionary, **which turns out to be a built-in method of `dict`**. This is why you are getting a `TypeError` saying that you can't iterate over a method.

The short answer to your problem is: Rename the `items` field to something else that isn't a built-in attribute or method of `dict`.

For example, the following will work:

``` python
from marshmallow import Serializer, fields, pprint

class Book(object):
    title = ''
    author = ''

class BookSerializer(Serializer):
    title = fields.String()
    author = fields.String()

class BookList(object):
    books = list()

class BookListSerializer(Serializer):
    books = fields.Nested(BookSerializer, many=True)


book1 = {'title': 'hello android', 'author': 'leejaycoke'}
book2 = {'title': 'hello iOS', 'author': 'tommy'}
book = {'books': [book1, book2]}

pprint(BookListSerializer(book).data)
# {"books": [{"author": "leejaycoke", "title": "hello android"}, {"author": "tommy", "title": "hello iOS"}]}
```

**Comment by leejaycoke** [comment]
Thank you very much.
I can't understand me why I'd naver tried to change attribute name (items).

**Comment by charalamm** [comment]
This answer solves the problem without having to change the key name but it may have a performance cost
https://github.com/marshmallow-code/marshmallow/issues/648#issuecomment-450184653
