### ISSUE TITLE
Argument lost in the documentation.

### ISSUE THREAD

**Issue by aguilera51284** [marshmallow-code/marshmallow#313]
Not if I'm wrong , but the argument ' ' in fields , lacks the tuple ' invalid ' . I can tell if I'm right or wrong

**Comment by sloria** [comment]
I'm not sure what part of the documentation you are referring to; can you please clarify which function/method/class you are talking about?

**Comment by aguilera51284** [comment]
upss sorry , is in api->fields->default_error_messages ,the ' invalid ' argument is lost in the example or if not defined elsewhere

**Comment by sloria** [comment]
The `default_error_messages` isn't really an argument; it's a class variable that all `Fields` have. To see the available keys for `error_messages`, it's easiest to view the source of the Field. See `Date`, for example: https://github.com/marshmallow-code/marshmallow/blob/cb88c32cf7ae238d313f518adda011f203da3151/marshmallow/fields.py#L913-L916.

I'd rather not document `default_error_messages` for every field, since, the `fields` module is currently autodoc'd, and not all Field subclasses override `default_error_messages`.

**Comment by aguilera51284** [comment]
thanks for the reply.
