### ISSUE TITLE
Raise a better exception if context is not available for Function

### ISSUE THREAD

**Issue by sloria** [marshmallow-code/marshmallow#326]
Currently, if the function passed to a `Function` field needs context and the Schema's context is `None`, the error is stored as a validation error.

``` python
class MySchema(Schema):
    foo = fields.Function(lambda obj, ctx: ctx['bar'].lower())

sch = MySchema()
sch.context = None
data, errs = sch.dump({})  # should raise an error
```

Instead, an error should be raised. Perhaps a `NoContextError`.

**Comment by DamianHeard** [comment]
I was poking through this code today and kind of wondered if it need to raise an exception at all. I guess it depends if you consider the `None` context as something meaningful and useful.

**Comment by sloria** [comment]
My thought was that `Function` and `Method` fields should assume that context is a dict. If it isn't a `dict`, the program should fail early (rather than waiting to raise `TypeError: 'NoneType' object has no attribute '__getitem__'`).

**Comment by DamianHeard** [comment]
I understand that logic. I guess in the case you've outlined you've explicitly set the context to `None`. And since by default a Schema's context will be initialized to `{}` that really is the only way things could get into that state. I was just suggesting that there might be a use case `None` is a useful context in it's own right. If that is not the case then doesn't it make more sense to not let the context be set to `None` in the first place?

**Comment by sloria** [comment]
> If that is not the case then doesn't it make more sense to not let the context be set to None in the first place?

Yes, that change would happen in concert with the change in exception type.

**Comment by sloria** [comment]
On second thought, I'm not sure this is a good idea. As @DamianHeard pointed out, a `Schema's` context gets initialized to `{}`. `context` can only be `None` if the user explicitly sets it to `None`. I don't see a reason for preventing the user from doing that.
