### ISSUE TITLE
Expectation/Request: "default" implies "required"

### ISSUE THREAD

**Issue by brettdh** [marshmallow-code/marshmallow#407]
I've seen the previous request to make `required=True` by default, and I don't disagree. Slightly more surprising, though, was that I can specify a `default` value but not have that value filled in if the field is not also `required`. I'd suggest that `default=<not 'missing'>` should imply `required=True`.

Note: the context wherein I noticed the default value wasn't getting filled in was in a validator. It's possible the behavior is localized to this context, and that the default value is set in e.g. the decorated function. I haven't tested that, though, because in my current usage the validation fails (missing default value) if I don't set `default=<value>, required=True`.

**Comment by brettdh** [comment]
...er, clearly I wrote this too soon, before realizing that specifying both `default` and `required` leads to very different, still surprising behavior: `ValidationError`s for fields with default values when not explicitly setting those fields in the query string (using webargs).

Maybe I am just confused about what `required` means, or maybe there is some weird interaction between these two.

**Comment by sloria** [comment]
There is no relationship between `required` and `default`, since `default` applies to _serialization_. From https://marshmallow.readthedocs.org/en/dev/api_reference.html#marshmallow.fields.Field:

> default – If set, this value will be used during serialization if the input value is missing. If not set, the field will be excluded from the serialized output if the input value is missing. May be a value or a callable.

It looks like what you want is the `missing` param:

> missing – Default deserialization value for the field if the field is not found in the input data. May be a value or a callable.

There was discussion in https://github.com/marshmallow-code/marshmallow/issues/112 about making fields required by default, but we ultimately decided against it. Feel free to comment on that issue if you would like to continue the discussion.
