### ISSUE TITLE
Support for object type hierarchies

### ISSUE THREAD

**Issue by maximkulkin** [marshmallow-code/marshmallow#412]
Consider the following use case: you have a hierarchy of object types each of which can have unique attributes and you want to be able to serialize all them in a generic manner. E.g. you have type Event with subtypes representing particular type of event and having attributes specific to that type of event. I want to return a list of all events thus this list can contain events of different types. I would like to create a schema per event type (the same way I create a subclass per event type) and have a union-like Schema that will encode event type in some attribute on serialization and will use this field to pick particular schema on deserialization. This can also be extended to types that are do not have common predecessor.

``` python
class FooSchema(marshmallow.Schema):
    foo = marshmallow.fields.String(required=True)

class BarSchema(Schema):
    bar = marshmallow.fields.Integer(required=True)
```

What I would like to do is to have mixed list of objects which schemas are above and have them serialize uniformly.

``` python
MyUberSchema().dump([Foo(foo='hello'), Bar(bar=123)], many=True).data
# => [{'type': 'foo', 'foo': 'hello'}, {'type': 'bar', 'bar': 123}]
```

Is there an existing way to do that and/or is this a valid use case ?

**Comment by jaguardev** [comment]
sounds like it could cover case with table inheritance and discriminators from sqlalchemy

also, it could be useful to have switch on "schema level" but not on "load" or "dump" level

**Comment by maximkulkin** [comment]
@jaguardev What is "switch on schema level" ? Could you elaborate this case.

**Comment by maximkulkin** [comment]
Added pull request https://github.com/marshmallow-code/marshmallow/pull/416 that contains implementation for above mentioned schema

**Comment by justanr** [comment]
I'd argue if you're using subclasses that have unique values that need to be serialized differently, then you should use separate schemas. Otherwise, you're violating the substitution principle  -- that is, if you have a subclass you _should_ be able to transparently substitute it in with no knowledge required on the caller's part.

That said, I have done this before for extremely special cases -- two objects that largely represent the data but are conceptually different and live at different REST endpoints but can be quietly processed in the same list.

Consider an album and a playlist. They're both collections of songs with an owner (artist and user respectively). But it's possible to process both with the same code, you just point the owner field at the correct URI and go.

**Comment by maximkulkin** [comment]
@justanr How would you create a single schema that will account for all fields in all subclasses ? I imagine that would be a nightmare with switches and conditional validation (and I'm still curious on your solution to this).

**Comment by maximkulkin** [comment]
Another example would be say you have an API that describes devices of some system. Devices can be of different type (e.g. storage devices, network devices, etc) with each type having it's own characteristics.

**Comment by justanr** [comment]
I'd boil the concepts down to a common interface. I find a lot of value in the commonality of objects, not their differences. But that's just my opinion.

You don't want to try accommodating all potential values a subclass could have, just the minimum viable subset.

What all fields are common to _all_ storage devices? Probably total storage, used storage, mount point, the UUID, device name. 

I ended using a using polymorphic field for my playlist/album differences. Mobile github is being schwifty, otherwise I'd link to it. But the interface was 100% the same for both albums and playlists, the only difference being where the end point the owner field pointed at.

**Comment by maximkulkin** [comment]
I agree, that sometimes you can fit your problem into tools you have available. My point is that sometimes you don't want to.

**Comment by maximkulkin** [comment]
I have created a separate package that provides this functionality: [marshmallow-oneofschema](https://github.com/maximkulkin/marshmallow-oneofschema)

**Comment by lafrech** [comment]
I was about to ask about the same use case and we found this issue and your `marshmallow-oneofschema` extension. We've been using it and it works a treat. Thanks @maximkulkin !

@sloria, would you consider integrating this in Marshmallow? It could be in an optional module. The point is to promote it for users seeking that feature and also to ensure future modifications in Marshmallow don't break it.
