### ISSUE TITLE
`attribute` asymmetry

### ISSUE THREAD

**Issue by itajaja** [marshmallow-code/marshmallow#450]
if I define a field like:

``` py
foo = fields.String(attribute="bar.baz")
```

then I can serialize `{'bar': {'baz': 'myvalue'}}` to `{'bar': myvalue}`. I'd expect this to be symmetric, but if I load I get to `{'bar': myvalue}` to `{'bar.baz': 'myvalue'}`. Is there a better way to flatten a nested value or am I missing something? This behavior is a little weird, is there a reason for this to be asymmetric?

**Comment by sloria** [comment]
I agree this behavior is not intuitive. Looks like dot-delimited attribute syntax isn't being respected upon deserialization.

I would gladly review and merge a PR for this.

**Comment by sloria** [comment]
I fixed this in https://github.com/marshmallow-code/marshmallow/commit/8d90fb9d67f74a7497437db32b0781f398e8449e . I'll release a hotfix shortly.

**Comment by sloria** [comment]
Fix is in 2.13.4 and 3.0.0b2.

**Comment by itajaja** [comment]
Thanks! Keep up the great work :)

**Comment by density** [comment]
This change actually turned out to be backwards incompatible (it visibly changes the way deserialization works). Luckily, I have tests to catch things like this but for our friends who aren't so lucky, we should be more careful about minor point releases (this was released with version 2.13.4) with backwards incompatible changes...

**Comment by sloria** [comment]
@density This was not considered a breaking change because it does not break any API contract (defined by documentation and tests) *and* goes against user expectation. Sorry for any inconvenience it may have caused you. We do take backwards-compatibility seriously, and we appreciate any feedback you can give in this regard.

**Comment by density** [comment]
No inconvenience caused!

**Comment by lafrech** [comment]
I can't help but quote [this xkcd](https://xkcd.com/1172/).

![Workflow](https://imgs.xkcd.com/comics/workflow.png)

**Comment by density** [comment]
😇😂
