### ISSUE TITLE
Handling of validation errors in some of the nested objects

### ISSUE THREAD

**Issue by jomag** [marshmallow-code/marshmallow#457]
Hi, let me start with an example:

``` python
from pprint import pprint
from marshmallow import post_load, Schema, fields, validate

class UserSchema(Schema):
    name = fields.String()
    age = fields.Integer(validate=[validate.Range(20, 100)])

    @post_load
    def make_user(self, state):
        return User(**state)

class User:
    def __init__(self, name, age):
        self.name = name
        self.age = age

    def __repr__(self):
        return "User(Hi, I'm %s and I'm %d years)" % (self.name, self.age)

class TeamSchema(Schema):
    members = fields.Nested(UserSchema, many=True)

class Team:
    def __init__(self, members):
        self.members = members

data = {
    'members': [
        { 'name': 'Ronny', 'age': 52 },
        { 'name': 'Johnny', 'age': 33 },
        { 'name': 'Conny', 'age': 93 },
    ]
}

# All team members are valid
u = TeamSchema().load(data)
pprint(u.data)

# Output:
# {'members': [User(Hi, I'm Ronny and I'm 52 years),
#              User(Hi, I'm Johnny and I'm 33 years),
#              User(Hi, I'm Conny and I'm 93 years)]}

# Oops, one team member will fail validation!
data['members'][1]['age'] = 13
u = TeamSchema().load(data)
pprint(u.data)

# Output:
# {'members': [{'age': 52, 'name': u'Ronny'},
#              {'name': u'Johnny'},
#              {'age': 93, 'name': u'Conny'}]}
```

So, when one of the nested fields fails validation, `post_load` will be skipped for all of them. Is this the expected behavior? In my current project the ideal handling would be to drop the user that fails to validate and return the others as `User`-instances.

**Comment by lafrech** [comment]
In marshmallow 3, Schema is always `strict`. You get a `ValidationError` if something goes wrong during deserialization. You can access the correctly-deserialized data as an attribute of the exception (`exc.valid_data`), but `post_load` is skipped like in MA2.

We seem to agree that calling `post_load` on only successful items without removing failed items would result in inconsistent types.

Removing an item because it partially failed would be problematic, because you'd be losing data, so it can't be the default behaviour. Also, in a list, the order and the index may matter and if you remove an element, you shift all the indexes.

I just did a test by replacing `Nested(many=True)` with `List(Nested())`. In this case, it is even worse, the whole data from the `List` field is considered invalid and there is nothing at all in `exc.valid_data` (https://github.com/marshmallow-code/marshmallow/issues/766).

**Comment by deckar01** [comment]
There are other problems with using `valid_data` after failed deserialization. There is no way to know if the partial results are otherwise valid without running the whole thing through the schema validation again. Also, the transformed output might not be considered valid input. In this example the members key could be missing or the value could be something other than a list.

You might need to relax the team schema and validate the members in a second pass.

```py
class TeamSchema(Schema):
    members = fields.Nested(fields.Dict, many=True)

    @post_load
    def ignore_invalid_members(self, data):
        loaded_users = [UserSchema().load(user_data) for user_data in data['members']]
        data['members'] = [user.data for user in loaded_users if not user.errors]
        return data
```

**Comment by sloria** [comment]
Closing this for now. Use @deckar01 's workaround above if you need to load partially valid nested data like that.
