### ISSUE TITLE
fields.Field's missing option with many=True, unexpected behavior

### ISSUE THREAD

**Issue by podhmo** [marshmallow-code/marshmallow#567]
marshmallow's fields.Field has two options.

- default
- missing

I wonder `default` is the hook (or default value) for serialization, and `missing` is the hook for deserialization.

## with many=True option, default is ok

when serialization, default option is correctly, I feel.

```python
from marshmallow import fields, Schema


class S(Schema):
    nums = fields.Integer(many=True, default=[1, 2, 3])

print(S().dump({}).data)
# {'nums': [1, 2, 3]}
```

## with many=true option,  missing is uncomfortable behavior

But,  when deserialization,  current marshmallow's behavior is not good. Maybe, I have misunderstanding for missing option.  Although, using missing option with `many=True`,  treating default value as collection is better, I think.

```python
from marshmallow import fields, Schema


class S(Schema):
    nums = fields.Integer(many=True, missing="[1, 2, 3]")

# this is error.
print(S().load({}))
# UnmarshalResult(data={}, errors={'nums': ['Not a valid integer.']})


# if missing's value is 1, error is not raised. but, this is not good, at least me.
class S2(Schema):
    nums = fields.Integer(many=True, missing="1")
print(S2().load({}))
# UnmarshalResult(data={'nums': 1}, errors={})
```

**Comment by maximkulkin** [comment]
The problem with your example is that you're not using `many=True` correctly. Most field types do not accept `many` option (at least the way you think). For field types other than Nested, `many` argument is treated as a *metadata*, some information that is stored in field type (that's why you do not get "unknown argument" errors), and as far as I can tell that metadata is not used in any way by the library itself.
In order to create a proper list of integers, you need to do
```python
class S(Schema):
    nums = fields.List(fields.Integer())
```
That way you could encode default/missing values there:
```python
class S(Schema):
    nums = fields.List(fields.Integer(), missing=[1, 2, 3])
```
The reason why `default` argument works for you is that when dumping it just takes whatever you put there and put into output, but for loading it actually tries to parse it (although you still need to supply it as a list of integers, not a JSON string of list of integers).

```python
class S(Schema):
    nums = fields.List(fields.Integer(), default=[4, 5, 6], missing=[1, 2, 3])


print S().dump({})
# => MarshalResult(data={u'nums': [4, 5, 6]}, errors={})
print S().load({})
# => UnmarshalResult(data={'nums': [1, 2, 3]}, errors={})
```

**Comment by lafrech** [comment]
```py
class S(Schema):
    nums = fields.List(fields.Integer(), missing=[1, 2, 3])
```
Is it hazardous to use a mutable as default/missing value like it is for functions/methods?

I mean is it possible to get weird behaviours because all instances of the Schema share the same instance and if it gets modified once, it is modified in the Schema class itself?

**Comment by maximkulkin** [comment]
@lafrech Yes, you are correct: it's dangerous to use mutable values (e.g. lists) as default/missing values. To workaround that you can use callable that will return those values:
```python
class S(Schema):
    nums = fields.List(fields.Integer(), missing=lambda: [1, 2, 3])
```

**Comment by podhmo** [comment]
OK. I've misunderstood the meaning about `many=True`,  for a collection value,  using fields.List instead of many option. I missed fields.List .

@lafrech, @maximkulkin  Thank you for replying correct answer.
