### ISSUE TITLE
Non ValidationError Exceptions still get silently put into errors list

### ISSUE THREAD

**Issue by svenstaro** [marshmallow-code/marshmallow#60]
For instance, if I forget importing ValidationError itself, I get a list like this:

`{
    "username": [
            "'Marshmallow' object has no attribute 'ValidationError'"
        ]
}`

Now, this should obviously this exception should not be caught by Marshmallow. I'm not sure why that even works. Any idea whether this is a bug or a problem on my side?

My code:

```
def duplicate_email_validator(email):
    <logic>
    raise ma.ValidationError("Email already exists")

class UserInputSchema(ma.Schema):
    username = ma.Email(validate=duplicate_email_validator, required=True)
    password = ma.String(required=True)

result, errors = UserInputSchema(strict=False).load(request.json)
```

**Comment by sloria** [comment]
The current behavior is for Fields to capture any uncaught exceptions (unless they are wrapped with `ForcedError`) and store them in the errors dictionary.

The idea was to save the field's from having to do much exception handling and instead allow the abstract `Field` class catch all the errors.

I realize now that this leads to undesired behavior when an exception is raised during deserialization that is unrelated to data formatting or type validation.

I am in the process of refactoring the fields so that each field is responsible for deciding which errors get stored in the errors dictionary.

Thanks for reporting this.
