### ISSUE TITLE
Support validator=, validators=, or validate_with=.

### ISSUE THREAD

**Issue by douglas-treadwell** [marshmallow-code/marshmallow#645]
In field constructors, validate=validation_function doesn't flow naturally in English.
An average person, before reading the docs, might think that a parameter named "validate" would take a boolean and turn validation on or off, like "strict".

For a single validator, Field(validator=is_lowercase) sounds more natural.
For multiple validators, Field(validators=[is_lowercase, is_alphanumeric]) sounds more natural.
For convenience, these could be aliases of the same method, although I can't think of a case where a developer-user of this API would not know whether they're validating with one or multiple functions.

**Comment by monotaro-yasushi-masuda** [comment]
+1 for validator. Even if validator accept multiple validators, it can be recognized as "a validator bulit with a combination of validators".
-1 for validate_with, parameter key better not to have particles, except the case such as valid_from and valid_to etc.

**Comment by lafrech** [comment]
I agree `validator` would be more natural than `validate`, and `validate_with` is too long.

Currently, `validate` accepts both a callable and a collection of callables and I'd rather stick to only one version, either `validator` or `validators`.

    validators=my_callable

definitely looks weird.

    validator=(collection of callables)

could do, like @monotaro-yasushi-masuda says, it is a compound validator so singular form is understandable, but it is still surprising to provide a collection to a singular argument.

The most natural thing, of course, would be to use `validators` and accept only collections. Besides, internally the value is stored as `self.validators`, so it is clearer to expose this to the caller, so that the parameter matches the attribute like for the other attributes.

But most of the time we only use one validator, so the shortcut allowing a callable is nice.

There's a trade-off here between clarity and practicality (and history).

Keeping the ability to pass only a callable would be nice. In this case, `validate` comes in handy precisely because it does not indicate whether it is plural or singular.

At least, keeping `validators` inside does not break introspection for third-party libs (like apispec).

**Comment by sloria** [comment]
> `validate` comes in handy precisely because it does not indicate whether it is plural or singular.

IIRC, this was the reason for choosing "validate." I wouldn't consider `validator=[list of callables]` any more natural than `validate=[...]`. `validator=callable` is slightly more natural than `validate=callable`, but I'm not sure it's worth the breaking change.

**Comment by sloria** [comment]
Closing this, as it has gone stale and I'm still not convinced that the OP is a significant improvement over the status quo to justify a breaking change.
