### ISSUE TITLE
Apply @validates decorator multiple times?

### ISSUE THREAD

**Issue by FrancescElies** [marshmallow-code/marshmallow#653]
Hi,

I have a question, is there any reason why I should not apply the decorator `@validates` two times after each other?

```
class ValidatesSchema(Schema):
    foo = fields.Int()
    bar = fields.Int()

    @validates('bar')
    @validates('foo')
    def validate_foo(self, value):
        if value != 42:
            raise ValidationError('The answer to life the universe and everything.')
```

In the tests and the docs decorator is only applied once to a given function.
I would like to apply the same validator to different fields.

Best regards & thanks in advance for your help

**Comment by ramshaw888** [comment]
You shouldn't apply it because it doesn't work (right now).

These decorators only support a single application (it takes the top one). I your example it will only validate the `bar` field.

Instead of multiple applications of the decorator, I would imagine the simplest solution would be to allow `validates` to optionally support a list of fields.

**Comment by FrancescElies** [comment]
thanks for your reply
