### ISSUE TITLE
skip_missing is not working for fields of type String

### ISSUE THREAD

**Issue by malexer** [marshmallow-code/marshmallow#71]
It seems that skip_missing option is working only if field will have None value.
In case if input dict will not have some key which is declared as String type we will have and empty string in result.

Sample code:

``` python
class UserSchema(Schema):
    first = String()
    last = String()

    class Meta:
        skip_missing = True


test_data = dict(
    first='Name',
)

sch = UserSchema()
print sch.dump(test_data)
```

**Comment by sloria** [comment]
Only `key:value` pairs for which `value=None` are skipped. This is intentional. marshmallow does not make assumptions about whether a falsy value--such as an empty string--is a "null" value or if it is a valid, user-provided value. We would not, for example, want to skip `0` for a `Number` field.

For now, you will have to explicitly set a String field's default to `None` for it to be skipped.

A more long-term solution would be to allow `Field` classes to define a set of null values that are skippable:

``` python
class String(Field):
    # values that are skipped when skip_missing=True
    NULL_VALUES = set([None, ''])

class List(Field):
    # can't use a set, because lists are unhashable
    NULL_VALUES = (None, [], tuple())
```

Thoughts?
