### ISSUE TITLE
Marshmallow doesn't merge nested data

### ISSUE THREAD

**Issue by ghost** [marshmallow-code/marshmallow#834]
```python
from marshmallow.schema import Schema, fields
class MyPayload(Schema):
    class ActionAdd(Schema):
        # Parameters for actionAdd
        item_name = fields.Str()

    class ActionRemove(Schema):
        # Parameters for actionRemove
        ref_number = fields.Int()

    add_items = fields.Nested(ActionAdd, many=True, dump_to="items")
    remove_items = fields.Nested(ActionRemove, many=True, dump_to="items")


data = {
    "add_items": [
        {
            "item_name": "notebook"
        }
    ],
    "remove_items": [
        {
            "ref_number": 10
        }
    ]
}

request_data, errors = MyPayload().dump(data)

>>> request_data
Out[3]: {'items': [{'item_name': 'notebook'}]}
```

In an example shown above I am trying to dump a dictionary that will construct a payload to my API. the set of attributes of "ActionAdd" is differ from "ActionRemove". They both need to be dumped to the same "items" dictionary. From the example you can see that the request_data is missing "ref_number". Once "item_name" is removed from "data" then "ref_number" will be visible in request_data. Whats wrong with my implementation ?

**Comment by deckar01** [comment]
I'm not sure that we should implicitly merge when duplicate keys are used for `dump_to`. I think we should error instead of silently overwriting data.

Have you tried implementing this behavior with a `post_dump` method instead of `dump_to`?

```
from marshmallow import Schema, fields, post_dump

class MyPayload(Schema):
    class ActionAdd(Schema):
        item_name = fields.Str()
    
    class ActionRemove(Schema):
        ref_number = fields.Int()
    
    add_items = fields.Nested(ActionAdd, many=True)
    remove_items = fields.Nested(ActionRemove, many=True)
    
    @post_dump
    def merge_items(self, data):
        data['items'] = data['add_items'] + data['remove_items']
        del data['add_items']
        del data['remove_items']
        return data
```

If the use case ever needs special ordering or conditional logic, this pattern would have to be used anyway.

**Comment by ghost** [comment]
Let me make the situation more clear.
So my final `data` item can have both `item_name` and `ref_number` included
```
data = {
    'add_items': [{
        'item_name': 'notebook',
        'ref_number': 51
    }],
   'remove_items': [{
        'item_name': 'table_lamp',
        'ref_number': 10
   }]
}
```

The thing here is that the endpoint where dumped data is being sent requires different input for adding/removing items thus i decided to redirect both fields to the "items" entry.
I prefer that marshmallow could support such feature though I am ok with your suggestion and in this case marshmallow must throw an error if such situation occurs.

**Comment by ghost** [comment]
I am just curious. Any followup on this ?

**Comment by deckar01** [comment]
Raising an error would probably be considered a breaking change that would need to be made in a major version. Since `dump_to` and `load_from` have been combined into `data_key` in v3, reusing it for two different fields during a load actually has a valid use case (to copy a data value to two different attributes). Raising an error for duplicate keys at dump time to avoid data overwriting might not be possible since it could be a desired operation if the fields are assumed to be the same value (which the schema suggests).

Considering the v3 API, the desired interface is really a `dump_only` field that accepts a list of attributes to dump from. If I needed this custom merge behavior in more than a few places, I might try to make a custom field. Something like `MergeList(attributes=('add_items', 'remove_items'), dump_only=True)`. Otherwise a schema hook should be sufficient for one off data transformations.

**Comment by lafrech** [comment]
In marshmallow v3, an error is raised in case of `attribute` or `data_key` collision (excluding `dump_only`/`load_only` fields): https://github.com/marshmallow-code/marshmallow/pull/992.

A custom field seems relevant to your need. Feel free to reopen if still stuck with this.
