### ISSUE TITLE
readthedocs points to an unreleased version

### ISSUE THREAD

**Issue by Tor1mo** [marshmallow-code/marshmallow#866]
I spent the better part of this day trying to figure out why my installation of marshmallow didn't have the constants INCLUDE, RAISE, etc.  After some digging, I figured out what the problem was: the default readthedocs link points to documentation for the yet unreleased dev version of the package. 

I think this should definitely be fixed or the docs should state the discrepancy in a more visible manner. At the very least, it should be made clear that the `$ pip install -U marshmallow --pre` under the `Get It Now` section` does not point to the same version which the documents describe.

**Comment by sloria** [comment]
I agree it's not ideal. The trouble is that `/latest` currently tracks the `dev` branch rather than the latest release. There doesn't seem to be way for readthedocs to have `/latest` point to the latest tagged release. I've opened an issue: https://github.com/rtfd/readthedocs.org/issues/4326.

I suppose one workaround would be to have a separate branch that is equal to the latest pre-release and point `/latest` to it. That adds another step to the release process, but suppose we can deal with it for now.

**Comment by lafrech** [comment]
Ideally, there would also be a way to display the docs for untagged `dev`, for a final verification before releasing, but it is not that important for pre-release versions.

**Comment by deckar01** [comment]
Having the default (latest) point to a pre-release version can also cause confusion. It would be nice if this was communicated more clearly. Jasmine uses a version index as their docs landing page.

https://jasmine.github.io/pages/docs_home.html

**Comment by sloria** [comment]
I don't think there's a straightforward way to generate a version index with Sphinx/RTD. I think the way to go might be

1. Add a `3.0` branch that is even with the latest 3.0 pre-release.
2. Redirect http://marshmallow.readthedocs.io/ to https://marshmallow.readthedocs.io/en/3.0/
3. Keep `/latest` pointed to `dev`?

Not sure about 3. We could also point to `/latest` to `3.0`. Which is more intuitive for users?

**Comment by lafrech** [comment]
I'm surprised so many users use the `--pre` version. I'd expect latest to be latest stable (`2.x`)...

Would it be possible to 

- 1/ Have a message on top of 2.x pages saying "This is the latest stable, for 3.0, see..." + link to latest 3.x pre tag)
- 2/ Have a message on top of 3.x pages saying "This is a pre-release, for 2.0, see..." + link to latest 2.x tag)
- 3/ Display 2.x as default and 3.x a latest
- 4/ Have another way to display latest `dev`

?

3/ is not necessary, especially if the messages are visible
4/ is not necessary either, the docs can be viewed locally and if an error is seen too late once, then it's not too late to issue a bugfix release

**Comment by sloria** [comment]
> 1/ Have a message on top of 2.x pages saying "This is the latest stable, for 3.0, see..." + link to latest 3.x pre tag)

+1. This is a good idea.

> 2/ Have a message on top of 3.x pages saying "This is a pre-release, for 2.0, see..." + link to latest 2.x tag)

I believe there's a way to do this automatically with Sphinx/RTD, as I've seen it on other projects. I do have this setting on RTD:

<img width="300" alt="edit advanced project settings read the docs 2018-07-03 17-44-28" src="https://user-images.githubusercontent.com/2379650/42245944-c182f8ee-7ee8-11e8-8f40-ac015cb02e7c.png">

but it doesn't seem to have any effect. I reported the issue here: https://github.com/rtfd/readthedocs.org/issues/4327

> 3/ Display 2.x as default and 3.x a latest

I'd like to keep the 3.x docs as the default, in order to encourage usage of 3.0. I think making 3.x the default is why so many users are already using `--pre` (though I have no data to back this claim 😈 ).

> 4/ Have another way to display latest dev

Sure, I can add the `dev` branch on RTD.

**Comment by lafrech** [comment]
2/ "non-stable nor latest". What does that mean? Display when version is neither stable nor latest? Could it be you don't see anything because 3.x is latest? I don't really get the point.

**Comment by sloria** [comment]
Apparently the warning banner feature isn't well-supported by RTD (https://github.com/rtfd/readthedocs.org/issues/4327#issuecomment-402307378).

I've gone ahead and added a 3.0 branch that is even with the latest pre-release. https://marshmallow.readthedocs.io/ now re-directs to https://marshmallow.readthedocs.io/en/3.0/ . `latest` still points to `dev`, but at least it's no longer the default. So let's call this issue closed.

As for the warning banners, I've opened a new issue: #871.
