### ISSUE TITLE
Better default error messages for validators

### ISSUE THREAD

**Issue by mcgfeller** [marshmallow-code/marshmallow#885]
The default error message for validators ('Not a valid choice.') is not really helpful. 

I suggest better default messages, for example:
- OneOf / ContainsOnly: 'invalid value: {input}; use one of {choices}.'
- Range: 'invalid value: {input}; must be between {min} and {max}.'

The error argument could be a callable as well, for example to restrict the enumeration of valid choices to a certain length. 

Thanks for Marshmallow and best regards,
Martin

**Comment by sloria** [comment]
Thanks @mcgfeller for the feedback.

We removed input values from the default error messages in https://github.com/marshmallow-code/marshmallow/commit/27992463466a7d0936f4cef000402f853ed6f944#diff-6b084e078a8ab4b51fd1616021309a42 to address #255 and to prevent cases where clients render unsafe user input.

However, I don't see why we couldn't show static values such as `{choices}`, `{min}`, and `{max}`. 

* OneOf: `Not one of {choices}.`
* ContainsOnly: `One or more of the choices you made was not in {choices}.`

**Comment by sloria** [comment]
To add to my previous point: DRF recently removed input values from error messages: https://github.com/encode/django-rest-framework/pull/5881 .

I still think it should be possible to include input values--it just shouldn't be the default.

**Comment by hdoupe** [comment]
@sloria said:
> I still think it should be possible to include input values--it just shouldn't be the default.

This makes sense to me. I'm working on a [project](https://github.com/hdoupe/ParamTools) where the error messages really need to include the input in order to be helpful. I'm willing to take a crack at implementing a non-default option to include the input values, if that is still desired behavior. If not, I can find a work around to satisfy my own needs.

P.S. Marshmallow has been a joy to work with. Thanks for this awesome project.

**Comment by sloria** [comment]
@hdoupe Feel free to send a PR to make it possible to include input values.

P.S. Thanks for the kind words!

**Comment by sloria** [comment]
This was done in #1155.
