### ISSUE TITLE
Provide end-user readable string in ValidationError

### ISSUE THREAD

**Issue by mcgfeller** [marshmallow-code/marshmallow#886]
The default string representation of ValidationError shows a Python dictionary structure, which may be hard to understand by non-programmers - for example: 

`{'field1': ['Missing data for required field.'], 'field2': ['Invalid data.']}`

I suggest to provide a `ValidationError.list()` method which returns a list of messages in the form:

```
['field1: Missing data for required field',
'field2: Invalid data',
'field3.nested1: Invalid data']
```

which can be `'; '.join(messages)` easily into a string or returned as bullets at the convenience of the caller. 

It is important that the nesting is handled properly; i.e., flattened using a delimiter. 

Thanks again and best regards,
Martin

**Comment by deckar01** [comment]
I agree that the dictionary is not a presentation suitable for a user, but neither is a list with flattened keys. I think the expectation is that the error messages are placed in your UI by your client, close to where the user inputs each value. A user probably shouldn’t be exposed to the request structure of an API, because it might not match the labels in the UI.

The `pandas` package has a `json_normalize` utility that flattens dictionaries in the way you describe.

**Comment by lafrech** [comment]
I also think this logic belongs to the client.

Closing for now. Anyone willing to suggest a way to achieve something like this, please comment.
